export type EndpointCategory = 'Weekend' | 'Telemetry' | 'Strategy' | 'Standings';
export type ScopeKey = 'meeting' | 'session' | 'driver' | 'year';

export interface EndpointConfig {
  key: string;
  label: string;
  path: string;
  category: EndpointCategory;
  docsAnchor: string;
  description: string;
  note?: string;
  fields: string[];
  scope: ScopeKey[];
  heroMetric?: string;
}

const docsBase = 'https://openf1.org/docs/#';

export const ENDPOINTS: EndpointConfig[] = [
  {
    key: 'meetings',
    label: 'Grand Prix',
    path: 'meetings',
    category: 'Weekend',
    docsAnchor: `${docsBase}meetings`,
    description: 'Liste des week-ends de Grand Prix et des essais, avec circuit, pays et dates.',
    note: 'Mis a jour chaque jour vers minuit UTC.',
    scope: ['year'],
    heroMetric: 'meeting_key',
    fields: [
      'meeting_key',
      'meeting_name',
      'meeting_official_name',
      'location',
      'country_name',
      'country_code',
      'circuit_short_name',
      'circuit_type',
      'date_start',
      'date_end',
      'year',
    ],
  },
  {
    key: 'sessions',
    label: 'Sessions',
    path: 'sessions',
    category: 'Weekend',
    docsAnchor: `${docsBase}sessions`,
    description: 'Toutes les sessions de piste: essais, qualifications, sprint et course.',
    note: 'Mis a jour chaque jour vers minuit UTC.',
    scope: ['meeting', 'year'],
    heroMetric: 'session_key',
    fields: [
      'session_key',
      'session_name',
      'session_type',
      'meeting_key',
      'country_name',
      'location',
      'date_start',
      'date_end',
      'year',
    ],
  },
  {
    key: 'drivers',
    label: 'Pilotes',
    path: 'drivers',
    category: 'Weekend',
    docsAnchor: `${docsBase}drivers`,
    description: 'Identite des pilotes, abreviations, couleurs d equipe et portraits.',
    scope: ['session'],
    heroMetric: 'driver_number',
    fields: [
      'driver_number',
      'full_name',
      'broadcast_name',
      'name_acronym',
      'team_name',
      'team_colour',
      'headshot_url',
      'country_code',
      'meeting_key',
      'session_key',
    ],
  },
  {
    key: 'weather',
    label: 'Meteo',
    path: 'weather',
    category: 'Weekend',
    docsAnchor: `${docsBase}weather`,
    description: 'Conditions meteo sur le circuit, echantillonnees chaque minute.',
    scope: ['meeting'],
    heroMetric: 'track_temperature',
    fields: [
      'date',
      'air_temperature',
      'track_temperature',
      'humidity',
      'pressure',
      'rainfall',
      'wind_direction',
      'wind_speed',
      'meeting_key',
      'session_key',
    ],
  },
  {
    key: 'race_control',
    label: 'Direction de course',
    path: 'race_control',
    category: 'Weekend',
    docsAnchor: `${docsBase}race-control`,
    description: 'Messages de direction de course: drapeaux, incidents, statut et penalites.',
    scope: ['session'],
    heroMetric: 'flag',
    fields: [
      'date',
      'category',
      'flag',
      'message',
      'scope',
      'sector',
      'lap_number',
      'driver_number',
      'meeting_key',
      'session_key',
    ],
  },
  {
    key: 'car_data',
    label: 'Telemetrie voiture',
    path: 'car_data',
    category: 'Telemetry',
    docsAnchor: `${docsBase}car-data`,
    description: 'Vitesse, acceleration, frein, rapport, regime moteur et DRS a haute frequence.',
    note: 'Environ 3,7 echantillons par seconde.',
    scope: ['session', 'driver'],
    heroMetric: 'speed',
    fields: [
      'date',
      'driver_number',
      'speed',
      'throttle',
      'brake',
      'rpm',
      'n_gear',
      'drs',
      'meeting_key',
      'session_key',
    ],
  },
  {
    key: 'location',
    label: 'Position XY',
    path: 'location',
    category: 'Telemetry',
    docsAnchor: `${docsBase}location`,
    description: 'Coordonnees approximatives de la voiture sur le trace.',
    note: 'Environ 3,7 echantillons par seconde.',
    scope: ['session', 'driver'],
    heroMetric: 'x',
    fields: ['date', 'driver_number', 'x', 'y', 'z', 'meeting_key', 'session_key'],
  },
  {
    key: 'position',
    label: 'Classement en piste',
    path: 'position',
    category: 'Telemetry',
    docsAnchor: `${docsBase}position`,
    description: 'Evolution de la position du pilote pendant la session.',
    scope: ['session', 'driver'],
    heroMetric: 'position',
    fields: ['date', 'driver_number', 'position', 'meeting_key', 'session_key'],
  },
  {
    key: 'laps',
    label: 'Tours',
    path: 'laps',
    category: 'Strategy',
    docsAnchor: `${docsBase}laps`,
    description: 'Temps au tour, secteurs, vitesses intermediaires et tours de sortie des stands.',
    scope: ['session', 'driver'],
    heroMetric: 'lap_duration',
    fields: [
      'lap_number',
      'lap_duration',
      'date_start',
      'driver_number',
      'duration_sector_1',
      'duration_sector_2',
      'duration_sector_3',
      'i1_speed',
      'i2_speed',
      'st_speed',
      'is_pit_out_lap',
      'meeting_key',
      'session_key',
    ],
  },
  {
    key: 'pit',
    label: 'Stand',
    path: 'pit',
    category: 'Strategy',
    docsAnchor: `${docsBase}pit`,
    description: 'Passages dans la voie des stands, durees et arrets.',
    scope: ['session', 'driver'],
    heroMetric: 'pit_duration',
    fields: [
      'date',
      'driver_number',
      'lap_number',
      'lane_duration',
      'pit_duration',
      'stop_duration',
      'meeting_key',
      'session_key',
    ],
  },
  {
    key: 'stints',
    label: 'Relais pneus',
    path: 'stints',
    category: 'Strategy',
    docsAnchor: `${docsBase}stints`,
    description: 'Relais, type de gomme et age des pneus au depart de chaque relais.',
    scope: ['session', 'driver'],
    heroMetric: 'stint_number',
    fields: [
      'driver_number',
      'stint_number',
      'compound',
      'lap_start',
      'lap_end',
      'tyre_age_at_start',
      'meeting_key',
      'session_key',
    ],
  },
  {
    key: 'intervals',
    label: 'Ecarts',
    path: 'intervals',
    category: 'Strategy',
    docsAnchor: `${docsBase}intervals`,
    description: 'Ecart avec le leader et intervalle avec la voiture devant.',
    note: 'Disponible surtout en course, mise a jour environ toutes les 4 secondes.',
    scope: ['session', 'driver'],
    heroMetric: 'gap_to_leader',
    fields: [
      'date',
      'driver_number',
      'interval',
      'gap_to_leader',
      'meeting_key',
      'session_key',
    ],
  },
  {
    key: 'overtakes',
    label: 'Depassements',
    path: 'overtakes',
    category: 'Strategy',
    docsAnchor: `${docsBase}overtakes`,
    description: 'Depassements en piste ou changements de position lies aux stands et penalites.',
    note: 'Donnees parfois incompletes en course.',
    scope: ['session'],
    heroMetric: 'position',
    fields: [
      'date',
      'overtaking_driver_number',
      'overtaken_driver_number',
      'position',
      'meeting_key',
      'session_key',
    ],
  },
  {
    key: 'team_radio',
    label: 'Radio equipe',
    path: 'team_radio',
    category: 'Strategy',
    docsAnchor: `${docsBase}team-radio`,
    description: 'Extraits de radio entre le pilote et son ingenieur.',
    note: 'Il s agit d une selection, pas de l archive complete.',
    scope: ['session', 'driver'],
    heroMetric: 'recording_url',
    fields: ['date', 'driver_number', 'recording_url', 'meeting_key', 'session_key'],
  },
  {
    key: 'session_result',
    label: 'Resultat session',
    path: 'session_result',
    category: 'Standings',
    docsAnchor: `${docsBase}session-result`,
    description: 'Classement final, points, tours completes et statuts d abandon.',
    scope: ['session'],
    heroMetric: 'position',
    fields: [
      'driver_number',
      'position',
      'points',
      'duration',
      'gap_to_leader',
      'number_of_laps',
      'dnf',
      'dns',
      'dsq',
      'meeting_key',
      'session_key',
    ],
  },
  {
    key: 'starting_grid',
    label: 'Grille de depart',
    path: 'starting_grid',
    category: 'Standings',
    docsAnchor: `${docsBase}starting-grid`,
    description: 'Ordre de depart et chrono de reference pour la prochaine course.',
    scope: ['session'],
    heroMetric: 'position',
    fields: ['driver_number', 'position', 'lap_duration', 'meeting_key', 'session_key'],
  },
  {
    key: 'championship_drivers',
    label: 'Championnat pilotes',
    path: 'championship_drivers',
    category: 'Standings',
    docsAnchor: `${docsBase}drivers-championship-beta`,
    description: 'Classement pilotes au championnat pendant ou apres une course.',
    note: 'Disponible uniquement pour les courses.',
    scope: ['session'],
    heroMetric: 'points_current',
    fields: [
      'driver_number',
      'points_current',
      'points_start',
      'position_current',
      'position_start',
      'meeting_key',
      'session_key',
    ],
  },
  {
    key: 'championship_teams',
    label: 'Championnat equipes',
    path: 'championship_teams',
    category: 'Standings',
    docsAnchor: `${docsBase}teams-championship-beta`,
    description: 'Classement constructeurs pendant ou apres une course.',
    note: 'Disponible uniquement pour les courses.',
    scope: ['session'],
    heroMetric: 'points_current',
    fields: [
      'team_name',
      'points_current',
      'points_start',
      'position_current',
      'position_start',
      'meeting_key',
      'session_key',
    ],
  },
];

export const ENDPOINT_GROUPS: EndpointCategory[] = ['Weekend', 'Telemetry', 'Strategy', 'Standings'];

export const ENDPOINT_MAP = new Map(ENDPOINTS.map((endpoint) => [endpoint.key, endpoint]));
